easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            controller: App\Controller\Admin\ArticleController
        Tag:
            class: App\Entity\Tag
            controller: App\Controller\Admin\TagController